UTENTI_CONNECTION_URL=jdbc:mariadb://localhost:3306/utenti
LOGIN_USER=login
LOGIN_PASS=login
LIBRI_CONNECTION_URL=jdbc:mariadb://localhost:3306/libri

BIBLIOTECA_USER=biblioteca
BIBLIOTECA_PASS=biblioteca
LETTORE_USER=lettore
LETTORE_PASS=LETTORE